version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "npm", "run", "build:production" ]
    volumes:
      - /srv/static/schedule_builder/dist:/frontend/dist:z
    environment:
      NODE_ENV: production
