version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv/static/schedule_builder/dist:/frontend/dist:z
    args:
      - MODE=:production
    environment:
      NODE_ENV: production
