version: "3"

services:
  database:
    image: postgres:15.3-bullseye
    environment:
      POSTGRES_USER: schedule_builder
      POSTGRES_PASSWORD: schedule_builder
    restart: unless-stopped
  backend:
    build: .
    image: schedule_builder_stg
    command: bash /schedule_builder/server/django_devserver.sh
    depends_on:
      - database
    environment:
      DJANGO_SETTINGS_MODULE: "schedule_builder.settings.dev"
      DB_HOST: database
      DB_USER: schedule_builder
      DB_PASS: schedule_builder
      FQDN: schedule_builder.com
      SCHEMA: https
  keydb:
    image: bitnami/keydb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  celery_worker:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: "schedule_builder.settings.dev"
      DB_HOST: database
      DB_USER: schedule_builder
      DB_PASS: schedule_builder
      FQDN: schedule_builder.com
      SCHEMA: https
    image: schedule_builder
    command: bash /schedule_builder/server/celery_worker.sh
