services:
  backend:
    build: .
    image: schedule_builder
    command: bash /schedule_builder/server/django_devserver.sh
    volumes:
      - .:/schedule_builder
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: "schedule_builder.settings.dev"
