# Generated by Django 4.2 on 2025-04-28 21:38

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="encrypted_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="encrypted_first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="encrypted_last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="encrypted_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="encrypted_sub_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="technician",
            name="encrypted_first_name",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technician",
            name="encrypted_last_name",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="technician",
            name="encrypted_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="therapyappointment",
            name="encrypted_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
