# Generated by Django 4.2 on 2024-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("appointments", "0003_block_therapist_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Therapist",
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["client", "technician", "day", "start_time"]},
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": ["content_type", "object_id", "day", "block"],
                "verbose_name_plural": "Availabilities",
            },
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="block",
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(default="09:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(default="09:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="eval_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="prescribed_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technician",
            name="requested_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("content_type", "object_id", "day", "block")},
        ),
    ]
