# Generated by Django 4.2 on 2025-04-28 21:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_encrypt_existing_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["encrypted_first_name", "encrypted_last_name"]},
        ),
        migrations.AlterModelOptions(
            name="technician",
            options={"ordering": ["encrypted_first_name", "encrypted_last_name"]},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="client",
            name="sub_notes",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="therapyappointment",
            name="notes",
        ),
        migrations.AlterField(
            model_name="client",
            name="encrypted_sub_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Notes regarding subbing.  E.G 'No males'"
            ),
        ),
    ]
