# Generated by Django 4.2 on 2025-04-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_client_options_alter_technician_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="technician",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="encrypted_notes",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="encrypted_first_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="encrypted_last_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="encrypted_notes",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="encrypted_sub_notes",
            new_name="sub_notes",
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="encrypted_first_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="encrypted_last_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="encrypted_notes",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="therapyappointment",
            old_name="encrypted_notes",
            new_name="notes",
        ),
    ]
