# Generated by Django 4.2 on 2024-12-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointment_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="appointments.block",
            ),
        ),
    ]
