# Generated by Django 4.2 on 2025-05-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_client_options_alter_technician_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapyappointment",
            name="therapy_type",
            field=models.CharField(
                choices=[
                    ("ot", "Occupational Therapy"),
                    ("st", "Speech Therapy"),
                    ("mh", "Mental Health"),
                ],
                default="ot",
                max_length=2,
            ),
        ),
    ]
