# Generated by Django 5.2 on 2025-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_therapyappointment_therapy_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_manually_maxed_out",
            field=models.BooleanField(
                default=False,
                help_text="Indicates this person will be considered maxed out on sessions regardless of their total hours.",
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="is_manually_maxed_out",
            field=models.BooleanField(
                default=False,
                help_text="Indicates this person will be considered maxed out on sessions regardless of their total hours.",
            ),
        ),
    ]
