# Generated by Django 4.2 on 2024-12-19 20:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_availability_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
