# Generated by Django 4.2 on 2025-01-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_block_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="in_clinic",
            field=models.BooleanField(default=False),
        ),
    ]
