# Generated by Django 5.2.4 on 2025-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_client_is_manually_maxed_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_preschool_or_adaptive",
            field=models.BooleanField(default=False),
        ),
    ]
