# Generated by Django 4.2 on 2025-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_appointment_in_clinic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": ["content_type", "object_id", "day", "start_time"],
                "verbose_name_plural": "Availabilities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="availability",
            name="end_time",
            field=models.TimeField(default="09:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="availability",
            name="start_time",
            field=models.TimeField(default="09:00:00"),
            preserve_default=False,
        ),
    ]
