# Generated by Django 5.2.4 on 2025-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0009_schedule_appointment_schedule_availability_schedule_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={
                ("content_type", "object_id", "schedule", "day", "start_time")
            },
        ),
    ]
