# Generated by Django 4.2 on 2025-04-01 06:17

from django.db import migrations


def undo_block_availability(apps, schema_editor):
    Availability = apps.get_model("appointments", "Availability")

    for availability in Availability.objects.all():
        availability.start_time = availability.block.start_time
        availability.end_time = availability.block.end_time
        availability.save()


def reverse(apps, schema_editor):
    Availability = apps.get_model("appointments", "Availability")

    for availability in Availability.objects.all():
        availability.start_time = None
        availability.end_time = None
        availability.save()


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_alter_availability_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            undo_block_availability,
            reverse_code=reverse,
        ),
    ]
