# Generated by Django 5.2.4 on 2025-09-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_alter_availability_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("client", "schedule", "day", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="therapyappointment",
            unique_together={("client", "schedule", "day", "start_time")},
        ),
    ]
