# Generated by Django 4.2 on 2025-04-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("appointments", "0010_undo_block_availability"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("content_type", "object_id", "day", "start_time")},
        ),
    ]
