# Generated by Django 5.2.6 on 2026-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_alter_appointment_unique_together_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["schedule", "client", "technician", "day", "start_time"]
            },
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": [
                    "schedule",
                    "content_type",
                    "object_id",
                    "day",
                    "start_time",
                ],
                "verbose_name_plural": "Availabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="therapyappointment",
            options={"ordering": ["schedule", "client", "day", "start_time"]},
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="therapyappointment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("client", "schedule", "day", "start_time"),
                name="appointment_unique_with_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", True)),
                fields=("client", "day", "start_time"),
                name="appointment_unique_without_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("content_type", "object_id", "schedule", "day", "start_time"),
                name="availability_unique_with_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", True)),
                fields=("content_type", "object_id", "day", "start_time"),
                name="availability_unique_without_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="therapyappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("client", "schedule", "day", "start_time"),
                name="therapy_appointment_unique_with_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="therapyappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", True)),
                fields=("client", "day", "start_time"),
                name="therapy_appointment_unique_without_schedule",
            ),
        ),
    ]
