# Generated by Django 4.2 on 2025-04-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_alter_availability_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="block",
        ),
    ]
