# Generated by Django 4.2 on 2025-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0012_remove_availability_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
