# Generated by Django 4.2 on 2025-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0013_appointment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="in_clinic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="availability",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
