# Generated by Django 4.2 on 2025-04-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_client_is_onboarding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technician",
            old_name="color",
            new_name="bg_color",
        ),
    ]
