# Generated by Django 4.2 on 2025-04-09 20:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0016_rename_color_technician_bg_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#ffffff", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
