# Generated by Django 4.2 on 2025-04-09 20:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0017_alter_technician_bg_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
