# Generated by Django 4.2 on 2025-04-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0018_technician_text_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="notes",
        ),
    ]
