# Generated by Django 4.2 on 2025-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0019_remove_availability_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="max_hours_per_day",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="technician",
            name="requested_hours",
            field=models.IntegerField(default=40),
        ),
    ]
