# Generated by Django 4.2 on 2025-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_availability_is_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="past_technicians",
            field=models.ManyToManyField(
                blank=True,
                help_text="Technicians that have worked with this client in the past.",
                related_name="past_clients",
                to="appointments.technician",
            ),
        ),
    ]
