# Generated by Django 4.2 on 2025-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0022_client_past_technicians"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="sub_notes",
            field=models.TextField(
                blank=True, help_text="Notes regarding subbing.  E.g 'No males'"
            ),
        ),
    ]
