# Generated by Django 4.2 on 2025-04-22 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0023_client_sub_notes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("client", "day", "start_time")},
        ),
        migrations.CreateModel(
            name="TherapyAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "therapy_type",
                    models.CharField(
                        choices=[
                            ("ot", "Occupational Therapy"),
                            ("st", "Speech Therapy"),
                        ],
                        default="ot",
                        max_length=2,
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_appointments",
                        to="appointments.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "day", "start_time"],
                "unique_together": {("client", "day", "start_time")},
            },
        ),
    ]
