# Generated by Django 4.2 on 2024-12-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailuser",
            options={
                "ordering": ("email",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
