# Generated by Django 5.2.4 on 2025-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_emailuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailuser",
            name="hover_cards_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable hover cards on the frontend for quick info on users and events.",
            ),
        ),
    ]
